### PR TITLE
Release to Sonatype instead

### PR DESCRIPTION
**Pull request by joshk0**
Repeated process from LiveRamp/daemon_lib#26

### CODE REVIEW

**Comment by joshk0** [comment]
@h-wang94 @cgardens ping

**Comment by h-wang94** [comment]
Oh oops, thanks for pinging. 
Idk if I'll have time to look at it this today / this afternoon. Will try to get to this by tomorrow if thats okay.

**Comment by joshk0** [comment]
no worries!

**Comment by h-wang94** [comment]
Looks good.

Consumers would need to make changes to pull from the new location now right?

**Comment by joshk0** [comment]
if the consumer is liveramp nothing needs to be done because artifactory merges all of our repos into a 'virtual' repo. other consumers would need to migrate eventually. I can work on that messaging when i think of destroying repository.liveramp.com ?

**Comment by joshk0** [comment]
Oh just realized I didn't update README.md with the new location. Doing that now.

**Pull request merged**
